---
title: "Untitled"
author: "Lyskova_Alisa"
date: "2024-08-31"
output: html_document
---

```{r}
library(tidyverse)
library(showtext)
library(showtextdb)

pink <- '#C6878F'
brown <- '#E07A5F'
blue <- '#3D405B'
green1 <- '#5F797B'
green2 <- '#81B29A'
yellow <- '#F2CC8F'
```

```{r}
file1 <- c("../data/vcf/ERR10963128_APOBEC-like.vcf")
sample_id <- c("ERR10963128")
file2 <- c("../data/APOBEC_targets.csv")
df1 <- read.csv(file1, sep = "\t", header = TRUE)
df2 <- read.csv(file2, sep = "\t", header = TRUE)
head(df1)
head(df2)
```
```{r}
df1 <- df1 %>% select('X.CHROM','POS', 'REF', 'ALT', 'nucl_pos_codon', 'parent_codon', 'parent_aa', 'child_codon', 'mutated_aa', 'mutation_category')
df1 <- df1 %>% mutate(type = "Observed APOBEC3-like")
colnames(df2) <- c('X.CHROM','POS', 'REF', 'ALT', 'nucl_pos_codon', 'parent_codon', 'parent_aa', 'child_codon', 'mutated_aa', 'mutation_category')
df2 <- df2 %>% mutate(type = "TC or GA target site")

print("Number of potential sites: ")
print(nrow(df2))

print("Number of observed APOBEC3-like sites: ")
print(nrow(df1))
```

```{r}
df <- rbind(df1,df2)
df_grouped <- df %>% group_by(mutation_category, type) %>% summarise(number = n())
df_grouped <- df_grouped %>% mutate(share = case_when(
  type == "TC or GA target site" ~ number/24695,
  type == "Observed APOBEC3-like" ~ number/631,
))
df_grouped
```

```{r}
p <- ggplot(df_grouped, aes(x=factor(mutation_category, level = c('nonsynonymous', 'synonymous', 'nonsense', 'intergenic')), y=share, fill=type)) + 
  geom_bar(stat = "identity", position=position_dodge()) +
  scale_fill_manual(values=c(blue,brown))+
  geom_text(aes(label=number), vjust=-0.3, color="black",
            position = position_dodge(0.9), cex=2)+
  theme_bw() +
  labs(title= 'Number of APOPBEC targets and observed APOBEC3-like sites by mutation category',
       subtitle = paste("sample ", sample_id),
      x = 'Mutation type',
      y = 'Proportion') +
    theme(text=element_text(size=6),
        plot.title = element_text(hjust = 0.5, size = 7),
        axis.text=element_text(size=6))

p

ggsave(paste('../data/vcf/pictures/APOBEC_targets_observed_', sample_id, '.png'), plot = p, height=4, width=5, dpi=300)
```
